name: Build & Push List

on:
  schedule:
    - cron: '0 3 * * *' # Runs every night at 03:00 UTC
  workflow_dispatch: # Allows manual trigger from GitHub UI
  push:
    branches:
      - main
    paths-ignore:
      - 'dist/**'
      - 'README.md'
      - 'CONTRIBUTING.md'
      - 'LICENSE'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Execute Build Script
        run: python build.py

      - name: Commit and Push Updated Lists
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add dist/
          if git diff --staged --quiet; then
            echo "No changes detected in bypass lists."
          else
            git commit -m "build: update ssl bypass FQDN list [${{ github.sha }}] [skip ci]"
            git push
          fi